name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Ensure compatibility with your project
          cache: 'npm'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Project
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: ./frontend
        run: npm run deploy
